### PR TITLE
upload biom files

### PR DESCRIPTION
**Pull request by reikopm**
Sample biom files from metabarcodes 12S, 16S, 18S, and COI. Data are from Monterey Bay, CA

### CODE REVIEW

**Comment by pbuttigieg** [comment]
Thabks @reikopm!

**Comment by jdeck88** [comment]
Thanks for uploading the samples.  Just a couple of issues to address before the merge:

1. can you provide samples that are any smaller?  It will be alot easier to get a grip on the samples if they are as small as possible to demonstrate the format.  These samples together are about 30Mb.  Great if they can fit in under 1Mb.  If it has to be 30Mb to demonstrate the format then we can work with it but smaller is better if possible.

2. in the README.md can you provide a description of what is in each file so it provides some context beyond what is in the files themselves?

3. the directory structure would work better i think like:
sample_data/MBARI

**Comment by reikopm** [comment]
Hello,
Yes, I'll work on it. 
-R
    On Wednesday, June 26, 2019, 08:51:41 AM PDT, John Deck <notifications@github.com> wrote:  
 
 
Thanks for uploading the samples. Just a couple of issues to address before the merge:
   
   -    
can you provide samples that are any smaller? It will be alot easier to get a grip on the samples if they are as small as possible to demonstrate the format. These samples together are about 30Mb. Great if they can fit in under 1Mb. If it has to be 30Mb to demonstrate the format then we can work with it but smaller is better if possible.

   -    
in the README.md can you provide a description of what is in each file so it provides some context beyond what is in the files themselves?

   -    
the directory structure would work better i think like:   
sample_data/MBARI

**Comment by pbuttigieg** [comment]
Hi @reikopm when you're done with file descriptions,  please request a review from me or ping me.

(for book-keeping xref #1)

**Comment by reikopm** [comment]
Hello,
I will do. Can you give me a little guidance on the descriptions you want. Did you want to know more about the biom format?

Many thanks,-R
    On Wednesday, June 26, 2019, 1:12:03 PM PDT, Pier Luigi Buttigieg <notifications@github.com> wrote:  
 
 
Hi @reikopm when you're done with file descriptions, please request a review from me or ping me.

(for book-keeping xref #1)

**Comment by pbuttigieg** [comment]
> I will do. Can you give me a little guidance on the descriptions you want. Did you want to know more about the biom format?

Mostly a description of what's in the various "slots" of the file (contingency table, metadata, taxonomy, etc), where that data came from, and if it follows any standards (e.g. MIxS).
Thanks!

**Comment by pbuttigieg** [comment]
@jdeck88 

>can you provide samples that are any smaller? It will be alot easier to get a grip on the samples if they are as small as possible to demonstrate the format. These samples together are about 30Mb. Great if they can fit in under 1Mb. If it has to be 30Mb to demonstrate the format then we can work with it but smaller is better if possible.

I think if it gets too small, the data won't really be useful for testing beyond simple exchange (e.g. checking for shared ASVs). 

We could prioritise pure exchange, but if we can work with real files we can do a lot more.

**Comment by pbuttigieg** [comment]
@reikopm shall we try to merge this week?

**Comment by reikopm** [comment]
Hello,
Apologies, I was on vacation last week.I am just getting back to working on the GLOMICON data and documentation.
I will keep you posted.
Regards,-R
    On Tuesday, July 2, 2019, 03:30:00 AM PDT, Pier Luigi Buttigieg <notifications@github.com> wrote:  
 
 
@reikopm shall we try to merge this week?

**Comment by pbuttigieg** [comment]
Many thanks @reikopm !

We're in good shape! just a little documentation and I can merge this PR.

**Comment by reikopm** [comment]
Hello,
I've finished the readme.md edits. Do you want to review it?I've made a bit of a mess with the data directories. I'm hoping that you can fix it on your end? 
There are the large complete biom files and I have smaller example biom files that John wanted which I am in the process of reviewing.
Regards, -R

    On Wednesday, July 10, 2019, 08:10:51 AM PDT, Pier Luigi Buttigieg <notifications@github.com> wrote:  
 
 
Many thanks @reikopm !

We're in good shape! just a little documentation and I can merge this PR.

**Comment by pbuttigieg** [comment]
Hi @reikopm 

Thanks for the revisions.

> I've made a bit of a mess with the data directories. I'm hoping that you can fix it on your end? 

I don't think I can (it would be guesswork in some cases). Please make sure that the directory structure is in good shape and that the documentation points to the right files.

> There are the large complete biom files and I have smaller example biom files that John wanted which I am in the process of reviewing.

Many thanks - so we should wait until you've prepped the smaller files prior to merging?

**Comment by reikopm** [comment]
Hello,
I'll work on the data directories. 
I will check the documents for correctness. The smaller files are being check and I think they are close to being submitted. 
I will keep you posted.
Regards, -R
    On Tuesday, July 30, 2019, 09:04:24 AM PDT, Pier Luigi Buttigieg <notifications@github.com> wrote:  
 
 
Hi @reikopm

Thanks for the revisions.


I've made a bit of a mess with the data directories. I'm hoping that you can fix it on your end?


I don't think I can (it would be guesswork in some cases). Please make sure that the directory structure is in good shape and that the documentation points to the right files.


There are the large complete biom files and I have smaller example biom files that John wanted which I am in the process of reviewing.


Many thanks - so we should wait until you've prepped the smaller files prior to merging?

**Comment by reikopm** [comment]
Hello Pier,
Apologies for the delay. I found a problem in the 12S biom file which took me some time to debug.
For your review I've moved the full biom files to reikopm/asvBiomXchange/sample_data/MBARI as John Deck requested. It took me several attempts to do this so there are a lot of commits as I manipulated the files.
Also as John Deck requested I've created the smaller example biom files. I've created a folder with a readme file for the example biom files. reikopm/asvBiomXchange/sample_data/MBARI/Example_biom_files
Please let me know of any modifications you would like. 
Regards,-Reiko
    On Tuesday, July 30, 2019, 09:04:24 AM PDT, Pier Luigi Buttigieg <notifications@github.com> wrote:  
 
 
Hi @reikopm

Thanks for the revisions.


I've made a bit of a mess with the data directories. I'm hoping that you can fix it on your end?


I don't think I can (it would be guesswork in some cases). Please make sure that the directory structure is in good shape and that the documentation points to the right files.


There are the large complete biom files and I have smaller example biom files that John wanted which I am in the process of reviewing.


Many thanks - so we should wait until you've prepped the smaller files prior to merging?

**Comment by raissameyer** [comment]
Hi @reikopm, 

I'll be working with Pier on this and will check out the biom files next week.

**Comment by pbuttigieg** [comment]
Hi @reikopm - Many thanks for your contributions. With @raissameyer's help in the next months, we'll drive this forward! 🍸

**Pull request merged**
